### ISSUE TITLE
Mod conflict between client and server

### ISSUE THREAD

**Issue by Raimdal** [MechanicalTitanModpackTeam/MechanicalTitan#55]
Hey When I try to join the server I put up with your download I get this
http://gyazo.com/8aec6a61f778e2bd99514f3c96fc6c4d

Would love to know how to fix this!

**Comment by BrizzleMFD** [comment]
make sure the versions of mods on both are the same and if that doesnt resolve it try the same thing attempted by the guy for issue #54
